applicationName: CWDS Dora

shiro:
  iniConfigs: ["file:${SHIRO_CONFIG_PATH:-config/shiro.ini}"]
  ini:
    main:
      perryRealm.validationUri: ${PERRY_VALIDATION_URL:-http://localhost:8080/perry/authn/validate}
      basicAuthRealm.basicAuthUser: ${DORA_BASIC_AUTH_USER:-user}
      basicAuthRealm.basicAuthPassword: ${DORA_BASIC_AUTH_PASSWORD:-pass}

  
swagger:
  templateName: swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.rest.resources
  title: CWDS Dora
  description: RESTful search services for the CWS New System.
  logo: images/CWDS-API-Logo-Horizontal.png
  loginUrl: ${PERRY_URL:-http://localhost:8080/perry/authn/login}
  logoutUrl: ${LOGOUT_URL:-http://localhost:8080/perry/authn/logout}
  spId: ${SP_ID:-} # service provider ID for Identity Mapping (defines security attributes for specific application)
  showSwagger: ${SHOW_SWAGGER:-true}
  jsonUrl: ${SWAGGER_JSON_URL:-http://localhost:8090/swagger.json}
  callbackUrl: ${SWAGGER_CALLBACK_URL:-http://localhost:8090/swagger}
  tokenUrl: ${SWAGGER_TOKEN_URL:-http://localhost:8080/perry/authn/token}

mode: ${DORA_MODE:-PROD}

elasticsearch:
  nodes: ${ES_NODES:-dora.dev.cwds.io:9200,localhost:9200}
  user: ${XPACK_USER:-elastic}
  password: ${XPACK_PASSWORD:-changeme}
  responseFieldFilters:
    person: 'config/filters/person_filter.groovy'
  xpack:
    enabled: ${XPACK_ENABLED:-true}

server:
  applicationConnectors:
  - type: http 
    port: ${APP_STD_PORT:-8080}
  adminConnectors:
  - type: http
    port: ${APP_ADMIN_PORT:-8081}
    
  requestLog:
    appenders:
      - type: console

sundial:
  thread-pool-size: 10
  shutdown-on-unload: true
  wait-on-shutdown: false
  start-delay-seconds: 0
  start-scheduler-on-load: true
  global-lock-on-load: false
  tasks: [startjob, stopjob, addcronjobtrigger]

logging:
  level: ${LOGLEVEL:-INFO}
  loggers:
    "gov.ca.cwds":
      level: INFO
  appenders:
    - type: console
      threshold: INFO
      timeZone: UTC
      target: stdout
      logFormat: '[%date{ISO8601}] [LEVEL=%level] [REMOTE_ADDRESS=%X{REMOTE_ADDRESS}] [REQUEST_ID=%X{REQUEST_ID}] [SESSION_ID=%X{SESSION_ID}] [STAFF_ID=%X{STAFF_ID}] [STAFF_COUNTY=%X{STAFF_COUNTY}] [RESPONSE_STATUS=%X{RESPONSE_STATUS}] [THREAD=%thread] [LOGGER=%logger] [MESSAGE=%message] [THROWABLE=%throwable]%n'

version: -UNUSED-
